seedgui/experimentos/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views



from . import views

app_name = 'experimentos'
urlpatterns = [
    path('', views.index, name='index'),
    path('lista_experimentos', views.lista_experimentos, name='lista_experimentos'),
    path('<int:experimento_id>/detalles/', views.ver_experimento, name='ver_experimento'),
    path('<int:experimento_id>/iniciar/', views.iniciar_experimento, name='iniciar_experimento'),
    path('<int:experimento_id>/resultados/', views.mostrar_resultados, name='resultados_experimento'),
    path('cargar_experimento', views.cargar_experimento, name='cargar_experimento'),
    path('<int:experimento_id>/descargar/', views.download_csv, name="descargar_datos")
]

seedgui/seedgui/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    path('test/', include('test.urls')),
    path('experimentos/', include('experimentos.urls')),
    path('accounts/login/', auth_views.LoginView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

seedgui/experimentos/models.py
from django.db import models

class Experimento(models.Model):
    """
    Clase que representa un experimento en el sistema.
    Contiene información sobre el nombre del experimento, fechas de inicio y finalización, frecuencia de captura de imágenes, cantidad de imágenes capturadas, observaciones, cantidad de semillas, estado y progreso del experimento.
    """
    nombre = models.CharField(max_length=50)
    fecha_inicio = models.DateTimeField(blank=True, editable=False, null=True)
    fecha_final = models.DateTimeField()
    frecuencia = models.FloatField()
    cantidad_imagenes = models.IntegerField(editable=False, null=True)
    imagenes_capturadas = models.IntegerField(editable=False, default=0)
    observaciones = models.CharField(max_length=200)
    cantidad_semillas = models.IntegerField()
    status = models.CharField(max_length=20, default="Creado", editable=False)
    progreso = models.FloatField(default=0, editable=False)

class Image(models.Model):
    """
    Clase que representa una imagen capturada en el contexto de un experimento.
    Almacena la imagen, la fecha de captura y se relaciona con un experimento.
    """
    photo = models.ImageField(upload_to='pics')
    fecha = models.DateTimeField()
    experimento = models.ForeignKey(Experimento, on_delete=models.CASCADE)

class Mask(models.Model):
    """
    Clase que representa una máscara asociada a una imagen capturada en el contexto de un experimento.
    Almacena la máscara, la fecha de creación y se relaciona con un experimento.
    """
    mask = models.ImageField(upload_to='masks')
    fecha = models.DateTimeField()
    experimento = models.ForeignKey(Experimento, on_delete=models.CASCADE)

class Semillas(models.Model):
    """
    Clase que representa datos de conteo de semillas para un experimento específico.
    Almacena la fecha de conteo, la cantidad de semillas germinadas y la cantidad de semillas no germinadas, y se relaciona con un experimento.
    """
    fecha = models.DateTimeField()
    germinadas = models.IntegerField()
    no_germinadas = models.IntegerField()
    experimento = models.ForeignKey(Experimento, on_delete=models.CASCADE)

seedgui/experimentos/forms.py
from django import forms

class UploadFileForm(forms.Form):
    """
    Clase que define un formulario para cargar archivos en la aplicación web.
    Permite a los usuarios cargar archivos, incluyendo un título y un archivo en sí.
    """
    title = forms.CharField(max_length=50)
    file = forms.FileField()

seedgui/experimentos/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Experimento
from .models import Image
from .models import Semillas
from .models import Mask
from datetime import datetime, timedelta
from django.utils import timezone
from .camera import VideoCamera
import time
from django.contrib.admin.views.decorators import staff_member_required
from .segmentation import count
import cv2
from .forms import UploadFileForm
import plotly.express as px
import pandas as pd
from plotly.offline import plot
import io
from .counter import Counter

# Create your views here.

@staff_member_required
def index(request):
    """
    Muestra una página de inicio para usuarios con permisos de administrador.
    """
    return render(request, "experimentos/index.html")

@staff_member_required
def lista_experimentos(request):
    """
    Muestra una lista de experimentos almacenados en la base de datos.
    """
    data = Experimento.objects.all()
    context = {'experimentos': data}
    return render(request, 'experimentos/lista_experimentos.html', context)

@staff_member_required
def ver_experimento(request, experimento_id):
    """
    Muestra los detalles de un experimento específico.
    """
    experimento = get_object_or_404(Experimento, pk=experimento_id)
    context = {'experimento': experimento}
    return render(request, 'experimentos/detalle.html', context)

@staff_member_required
def iniciar_experimento(request, experimento_id):
    """
    Inicia un experimento específico, realiza capturas de imágenes y realiza el conteo de objetos en las imágenes.
    """
    experimento = get_object_or_404(Experimento, pk=experimento_id)

    experimento.fecha_inicio = timezone.now()
    experimento.status = 'Iniciado'

    tiempo_total = (experimento.fecha_final - experimento.fecha_inicio).total_seconds() / 3600
    total_imgs = int(tiempo_total / experimento.frecuencia)
    experimento.cantidad_imagenes = total_imgs
    experimento.save()

    camera = VideoCamera(Image)
    counter = Counter("./yolov8.tflite")

    for i in range(total_imgs):
        fecha = datetime.now()
        fecha_conteo = timezone.now()
        path, image = camera.save_frame(fecha, experimento)
        out_path = path.replace("images", "detection")

        result, count_ = counter.predict(image)

        conteo = Semillas(fecha=fecha_conteo, germinadas=count_['germinated'], no_germinadas=count_['no_germinated'], experimento=experimento)
        conteo.save()

        cv2.imwrite(out_path, result)
        mask = Mask(mask=out_path, experimento=experimento, fecha=fecha)
        mask.save()

        time.sleep(experimento.frecuencia * 3600)

        progreso = ((i + 1) / total_imgs) * 100
        experimento.progreso = progreso
        experimento.imagenes_capturadas += 1
        experimento.save()

    experimento.status = 'Finalizado'
    experimento.save()

    return HttpResponse("Experimento terminado.")

@staff_member_required
def mostrar_resultados(request, experimento_id):
    """
    Muestra los resultados de un experimento, incluyendo imágenes, máscaras y datos de conteo.
    """
    experimento = get_object_or_404(Experimento, pk=experimento_id)

    images = Image.objects.filter(experimento=experimento)
    masks = Mask.objects.filter(experimento=experimento)
    conteo = Semillas.objects.filter(experimento=experimento)

    if experimento.status == "Creado":
        conteo_data = [
            {
                'Fecha': 0,
                'Germinadas': 0,
                'No Germinadas': 0,
            }
        ]
    else:
        conteo_data = [
            {
                'Fecha': x.fecha,
                'Germinadas': x.germinadas,
                'No Germinadas': x.no_germinadas,
            } for x in conteo
        ]

    df = pd.DataFrame(conteo_data)
    
    fig = px.line(df, x="Fecha", y=["Germinadas", "No Germinadas"], markers=True)
    fig.update_layout({
        'plot_bgcolor': 'rgba(0, 0, 0, 0)',
        'paper_bgcolor': 'rgba(0, 0, 0, 0)',
    })
    fig.update_xaxes(showline=True, linewidth=2, linecolor='black', gridcolor="LightGray")
    fig.update_yaxes(showline=True, linewidth=2, linecolor='black', gridcolor="LightGray")
    lista = zip(images, masks, conteo)
    fig_plot = plot(fig, output_type="div")
    context = {'experimento': experimento, 'lista': lista, 'plot_div': fig_plot}

    return render(request, 'experimentos/resultados.html', context)

@staff_member_required
def cargar_experimento(request):
    """
    Muestra una página para cargar un nuevo experimento.
    """
    return render(request, 'experimentos/cargar_experimento.html')

# Imaginary function to handle an uploaded file.
def handle_uploaded_file(f):
    with open('some/file/name.txt', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'])
            return HttpResponseRedirect('/success/url/')
    else:
        form = UploadFileForm()
    return render(request, 'upload.html', {'form': form})

def download_csv(request, experimento_id):
    """
    Descarga los datos de conteo de un experimento en formato CSV.
    """
    experimento = get_object_or_404(Experimento, pk=experimento_id)

    conteo = Semillas.objects.filter(experimento=experimento)

    if experimento.status == "Creado":
        conteo_data = [
            {
                'Fecha': 0,
                'Germinadas': 0,
                'No Germinadas': 0,
            }
        ]
    else:
        conteo_data = [
            {
                'Fecha': x.fecha,
                'Germinadas': x.germinadas,
                'No Germinadas': x.no_germinadas,
            } for x in conteo
        ]

    df = pd.DataFrame(conteo_data)

    csv_bytes = io.BytesIO()
    df.to_csv(csv_bytes, index=False, encoding='utf-8')
    csv_bytes.seek(0)

    response = HttpResponse(csv_bytes, content_type='text/csv')
   

seedgui/experimentos/templates/experimentos/cargar_experimento.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cargar Experimento</title>
</head>
<body>
    <h1>Cargar un experimento nuevo</h1>
    <hr>
    <input type="file" webkitdirectory mozdirectory accept="image/*" />
</body>
</html>

seedgui/experimentos/templates/experimentos/detalle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Experimento {{experimento.id_experimento}}</title>
</head>
<body>
    <h1>Experimento {{experimento.nombre}}</h1>
    <h2>Detalles:</h2>
    <ul>
        <li>id: {{experimento.id}}</li>
        <li>Nombre: {{experimento.nombre}}</li>
        <li>Observaciones: {{experimento.observaciones }}</li>
        <li>Fecha inicio: {{experimento.fecha_inicio}}</li>
        <li>Fecha fin: {{experimento.fecha_final}}</li>
        <li>Frecuencia: {{experimento.frecuencia}}</li>
        <li>Cantidad semillas: {{experimento.cantidad_semillas}}</li>
        <li>Cantidad imagenes: {{experimento.cantidad_imagenes}}</li>
        <li>Status: {{experimento.status}}</li>
        <li>Progreso: {{experimento.progreso}}%</li>
    </ul>

    <h2>Acciones:</h2>

    {% if experimento.status == 'Creado' %}
    <ul> 
        <li><a href="/experimentos/{{experimento.id}}/iniciar">Iniciar</a></li>
        <li><a href= "/admin/experimentos/experimento/{{experimento.id}}/change/">Editar</a></li>
    </ul>
    {% endif %}

    {% if experimento.status == 'Iniciado' %}
    <ul> 
        <li>Ver avance</li>
        <li>Parar</li>
    </ul>
    {% endif %}

    {% if experimento.status == 'Finalizado' %}
    <ul> 
        <li><a href="/experimentos/{{experimento.id}}/resultados">Ver resultados</a></li>
    </ul>
    {% endif %}


</body>
</html>

seedgui/experimentos/templates/experimentos/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menú Experimentos</title>
    {% load static %}
    <link rel="icon" href="{% static "seedgui/media/seed.png" %}">
    <link rel="stylesheet" href="../../static/experimentos/styles.css" />
</head>
<body>
    <div class="container center-y">
        
            <h1>Menú de Experimentos</h1>
            <hr class="lines">
        
            <form action="/admin/experimentos/experimento/add/" method="get">
                <button>Crear Experimento</button>
            </form>
        
            <form action="{% url 'experimentos:cargar_experimento' %}" method="get">
                <button>Cargar Experimento</button>
            </form>
        
            <form action="{% url 'experimentos:lista_experimentos' %}" method="get">
                <button>Ver Experimentos</button>
            </form>
        
            <form action="../" method="get">
                <button>Volver a inicio</button>
            </form>
            <hr class="lines">
    
    </div>
</body>
</html>

seedgui/experimentos/templates/experimentos/lista_experimentos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Experimentos</title>
    {% load static %}
    <link rel="icon" href="{% static "seedgui/media/seed.png" %}">
    <style>
        body {
            font-family: 'Roboto', sans-serif !important;
        }
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap');
        form button {
            min-width: 300px; 
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 10px 20px;
            margin: 10px;
            border-radius: 5px;
            font-size: 24px;
            cursor: pointer;
            box-shadow: #BFBFBF ;
        }

        form button:hover {
            background-color: #3E8E41;
        }
        body {
            background-color: #f2f2f2;
        }

        .card {
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            margin: 20px;
            overflow: hidden;
            text-align: center;
            font-family: arial;
            display: flex;
            flex-direction: row;
        }

        .status-circle.Creado{
            border-radius: 50%;
            width: 15px;
            height: 15px;
            margin: 15px;
            background-color: gray;
        }

        .status-circle.Iniciado{
            border-radius: 50%;
            width: 15px;
            height: 15px;
            margin: 15px;
            background-color: orange;
        }

        .status-circle.Finalizado{
            border-radius: 50%;
            width: 15px;
            height: 15px;
            margin: 15px;
            background-color: green;
        }


        .title {
            font-size: 20px;
            font-weight: bold;
            margin: 10px;
        }

        .status {
            font-size: 16px;
            margin: 10px;
            align-self: center;
        }

        .card-link {
            display: block;
            color: #000000;
            text-decoration: none;
            padding: 10px;
            transition: background-color 0.3s;
            flex: 1;
        }

        .card-link:hover {
            background-color: #f2f2f2;
        }


        @media screen and (max-width: 768px) {
            .card {
                width: 90%;
                margin: 10px auto;
            }
        }

        .settings {
        position: relative;
        display: inline-block;
        margin: 10px;
        }

        .settings-btn {
            background-color: transparent;
            border: none;
            cursor: pointer;
        }

        .dot {
            display: block;
            width: 3px;
            height: 3px;
            margin: 3px;
            background-color: #000;
            border-radius: 50%;
        }

        .settings-menu {
            position: absolute;
            bottom: 25px;
            right: -10px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            padding: 10px;
            display: none;
            margin:15;
        }

        .settings:hover .settings-menu {
            display: block;
        }

        .settings-menu a {
            display: block;
            text-decoration: none;
            color: #000;
            padding: 5px 10px;
            font-size: 16px;
        }

        .settings-menu a:hover {
            background-color: #f2f2f2;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
    </style>
</head>
<body>
    <h1 style="text-align: center; margin-top: 40px;">Lista de Experimentos</h1>

    <div style="display: flex; flex-wrap: wrap;">
        {% for x in experimentos %}
        <div class="card">
            <div class="status-circle {{x.status}}">
            </div>
            <a class="card-link {{x.status}}" href="{% url 'experimentos:resultados_experimento' x.id %}">
                <h2 class="title">{{x.nombre}}</h2>
                <p class="status">{{x.status}}</p>
                <p class="status">{{x.progreso|floatformat:-2}} %</p>
                <p class="status">{{x.imagenes_capturadas}}/{{x.cantidad_imagenes}}</p>
            </a>
            <div class="settings">
                <button class="settings-btn">
                    <span class="dot"></span>
                    <span class="dot"></span>
                    <span class="dot"></span>
                </button>
                <div class="settings-menu">
                    <a href="/admin/experimentos/experimento/{{x.id}}/change/">Editar</a>
                    <a href="/admin/experimentos/experimento/{{x.id}}/delete/">Eliminar</a>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="card">
            <a class="card-link" href="/admin/experimentos/experimento/add/">
                <h2 class="title">Crear Experimento</h2>
                {% load static %}
                <img src="{% static "seedgui/media/new-page.png" %}" alt="new" height=50px/>
            </a>
        </div>
        <div class="card">
            <a class="card-link" href="{% url 'experimentos:cargar_experimento'%}">
                <h2 class="title">Cargar Experimento</h2>
                {% load static %}
                <img src="{% static "seedgui/media/upload.png" %}" alt="new" height=50px/>
            </a>
        </div>
    </div>
    <div class="container center-y">
    <form action="{% url 'index' %}" method="get">
        <button>Inicio</button>
    </form>
    </form>
    </div>
</body>
</html>

seedgui/experimentos/templates/experimentos/resultados.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css">
    {%load static%}
    <link rel="icon" href="{% static "seedgui/media/seed.png" %}">
    <title>Resultados</title>
    <style>
        body {
            font-family: 'Roboto', sans-serif !important;
            background-color: #f2f2f2;
        }
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap');
        .wrapper-counter {
            display: flex;
            flex: row;
            justify-content: center;
            align-items: center;
            align-self: center;
            align-content: center;
        }

        .wrapper-counter img {
            padding-right: 10px;
        }

        .wrapper-counter span {
            font-size: 22px;
            text-align: center;
        }

     
        .swiper-slide {
            margin-left: auto;
            margin-right: auto;
            text-align: center;
        }

        /* .swiper-wrapper {
            text-align: center;
        } */

        .status-circle.Creado{
            border-radius: 50%;
            width: 15px;
            height: 15px;
            margin: 15px;
            background-color: gray;
        }

        .status-circle.Iniciado{
            border-radius: 50%;
            width: 15px;
            height: 15px;
            margin: 15px;
            background-color: orange;
        }

        .status-circle.Finalizado{
            border-radius: 50%;
            width: 15px;
            height: 15px;
            margin: 15px;
            background-color: green;
        }
        .result-span{
            height:50px;
            margin-right: 20px;
            margin-bottom: 20px;
            position: relative;
            top:20px; 
        }

        form button {
            min-width: 300px; 
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 10px 20px;
            margin: 10px;
            border-radius: 5px;
            font-size: 24px;
            cursor: pointer;
            box-shadow: #BFBFBF ;
        }

    </style>
</head>
<body>
    <h1>{{experimento.nombre}} ({{experimento.status}})</h1>

    <ul>
        <li>Observaciones: {{experimento.observaciones }}</li>
        <li>{{experimento.fecha_inicio}} - {{experimento.fecha_final}}</li>
        <li>Período entre capturas: {{experimento.frecuencia}} H</li>
        <li>Imágenes: {{experimento.imagenes_capturadas}}/{{experimento.cantidad_imagenes}}</li>
        <li>Progreso: {{experimento.progreso|floatformat:-2}}%</li>
    </ul>

    <div class="swiper mySwiper">
        <div class="swiper-wrapper">
            {% for x in lista %}
            <div class="swiper-slide">
                <div class="caption">
                    <p>{{ x.0.fecha }}</p>
                    {% load static %}
                    
                    <div class="wrapper-counter">
                        <img display="inline-block" src="{% static "seedgui/media/germ_seed.png" %}" alt="germinated seed" height=50px/>
                        <span class="result-span">{{ x.2.germinadas }}</span>
                    
                        <img display="inline-block" src="{% static "seedgui/media/non_germ_seed.png" %}" alt="germinated seed" height=50px/>
                        <span class="result-span">{{ x.2.no_germinadas }}</span>
                    </div>
                </div>
                <img display="inline-block" src="{{ x.0.photo.url }}">
                <img display="inline-block" src="{{ x.1.mask.url }}">
            </div>
            {% endfor %} 
        </div>
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-pagination"></div>
    </div>

    {% block content %}
    {% autoescape off %}
        {{ plot_div }}
    {% endautoescape %}}
    {% endblock content %}

    <div>
        <form action="" method="get">
            <button>Descargar Reporte</button>
        </form>
    
        <form action="{% url 'experimentos:descargar_datos' experimento.id %}" method="get">
            <button>Descargar Datos</button>
        </form>
    </div>

    {% if experimento.status == 'Creado' %}

    <div>
        <form action="/experimentos/{{experimento.id}}/iniciar" method="get">
            <button>Iniciar Experimeto</button>
        </form>
    </div>

    {% endif %}

    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/swiper/js/swiper.min.js"></script>

    <script>
        var swiper = new Swiper(".mySwiper", {
        spaceBetween: 30,

        effect: 'fade',
        fadeEffect: {
            crossFade: true
        },
        pagination: {
            el: ".swiper-pagination",
            type: "progressbar",
            },

        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
            },
        observer: true, 
        observeParents: true,
        observeSlideChildren: true
        });
    </script>
</body>


    
</html>